apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ldjk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-ldjk
    app.kubernetes.io/part-of: quinoa-wind-turbine
  name: devfile-sample-code-with-quarkus-ldjk
  namespace: nvinto-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ldjk
status:
  loadBalancer: {}
